### ISSUE TITLE
Unable to bundle with rollup

### ISSUE THREAD

**Issue by SimenB** [jonschlinkert/class-utils#3]
See https://github.com/micromatch/micromatch/issues/107

Rollup throws when trying to bundle this library.

Repro: https://github.com/SimenB/micromatch-rollup

**Comment by jonschlinkert** [comment]
thanks! I'll get this fixed

**Comment by jonschlinkert** [comment]
Should be fixed, really sorry this took so long.

**Comment by SimenB** [comment]
Awesome, thanks!
