### ISSUE TITLE
test failure with node 8

### ISSUE THREAD

**Issue by kapouer** [jonschlinkert/class-utils#4]
`cu.nativeKeys(App.constructor)` now returns `['length', 'name', 'prototype']` instead of `['length', 'name', 'caller']`.

**Comment by jonschlinkert** [comment]
thanks for creating the issue, and sorry for the delay. Marking this as a bug, I'll take a look as soon as I have a chance. I think there is a better way to handle the logic in that function. (pr would also be great)
